= Avimitin's Commit Convention {version}
Avimitin <avimitin@gmail.com>
// attr
:version: 0.2.0
:sectnums:
:toc: left
// cite
:github-url: https://github.com/Avimitin/commit-convention
:cclink: https://www.conventionalcommits.org/en/v1.0.0/
:asciidoc-homepage: https://asciidoctor.org/

Avimitin's commit convention is a commit style that keep simplicity and semantic
version marker.

== Format

----
<type>[!][,][component]: <description>

[body]

[footer]
----

[quote,]
Component in `[]` means optional, other are required.

This is similar to the {cclink}[Conventional Commits 1.0.0], but it trim
the long commit type.
I don't want the "refactor(scope)" text or other type text ocupy so much space.

As the conventional commits 1.0.0 use lower case letter in title, I replace
the giant text with the below convention:

* new: A new feature, equal to `feat`.
* fix: A fix commit, equal to `fix`.
* rft: A refactor commit, equal to `refactor`.
* chr: A commit don't affect the main code, equal to `chore`.
* doc: A commit related to document stuff.
* Attach `!` after the type if the commit contains breaking change.

So after this new design, the commit message will be like:

.Example
----
new,socket: implement new API `read()`
rft,buffer: reduce the write_buf() complexity to O(n)
fix,io/net: fix CVE-2021-9999
doc,readme: add guideline for using docker build

# breaking change
rft!,lib/crypto: drop the SHA-1 library support

# module name can be ignored
new: implement new module parser
chr: reformat the code
----

I choose the `,` as divider between prefix and component.
It is optional. And it makes the title looks more straightforward.
Besides, it helps generate a clearer oneline git commit history.

== Title

Title is really important. For developer, you can generate change log and
semantic version by `git log --oneline`. For user, they can know if the
developer made any important changes. So a proper title helps all the
people.

=== length

Title should be wrap in 50 Latin characters.

=== type

Use `N` type when you implement new API or import a new library. Use `F`
type when you fix a bug. Use the `R` type when you modify existing code.
And use `C` when you edit a document, docker file, CI file or anything
else that will not change the main code.

=== module

Except the type mark, all the text in title should be lower case. If the
module contains upper case like `README` or `TCP`, convert them to lower
case. If you have module named like `ipParser`, convert them to snake case
like `ip_parser`.

=== description

The first word of the title *should* be lower case and *must* be a verb.
Don't end with a period and don't attach any tense on it. You *must* write
the commit in the imperative.

For example:

This is good::

----
R/subsystem: refactor subsystem X for readability
C/readme: update getting started documentation
R!/api: remove deprecated methods
C/release version 1.0.0
----

And this is bad::

----
F/fixed bug with Y              ==> don't use tense
R/changing behavior of X        ==> don't use tense
F/more fixes for broken stuff   ==> use verb to make order
N/sweet new API methods         ==> there is no verb
----

A rule of thumb is to fill this sentence:
"This patch will modify the project to...".

Good Example::

* This patch will modify the project to refactor subsystem X for readability
* This patch will modify the project to update getting started documentation
* This patch will modify the project to remove deprecated methods
* This patch will modify the project to release version 1.0.0

So now the none-imperative commit are not working::

* This patch will modify the project to fixed bug with Y
* This patch will modify the project to changing behavior of X
* This patch will modify the project to more fixes for broken stuff
* This patch will modify the project to sweet new API methods

== Body

=== General

Body is optional. You can use any markup language that is well-knowing
in the body section. And you should write down what you have done and
why you did this. Don't write about how you do this.

If you are woring on a new PR, remember to attach the issue ID and PR ID.

Also if this commit contains breaking change, remember to attach
`BREAKING CHANGE:` to told what has been change at the end of the body
section. See the section "Full Example" for details.

=== Recommend format

I recommend using the asciidoc format.
It is a powerful markup language.
You can learn it from the {asciidoc-homepage}[asciidoc document].

"Use AsciiDoc for document markup.
Really.
It's actually readable by humans,
 easier to parse and way more flexible than XML."
-- Linux Torvalds

However, I only recommend you to use the basic asciidoc format.
Don't use too much asciidoc syntax.
It will confused other user.
My daily practice are listed below:

[pass]
<details>
<summary>Click to expand!</summary>
....
= Section

`short code`

[rust]
----
code block
----

* item 1
* item 2

{ref}[url]

:ref: https://github.com/Avimitin/commit-convention
....
[pass]
</details>

The most useful feature of the asciidoc format for our commit is attribute.
With this feature, you can put all the links at the bottom of the commit,
 and then reference it within the commit.
It will prevent some super long URL from cluttering up the commit message.

=== One Line Per Sentence

Besides, I recommend using one line per sentence.
Imaging you are editing a large paragraph, and you find yourself have syntax
error at the previous sentences.
You remove or add new word, it cause the editing line over 80 characters.
So you have to edit the whole paragraph to fit in 80 characters per line.

:one-sentence-per-line: https://rhodesmill.org/brandon/2012/one-sentence-per-line/
So as you are using asciidoc format, I recommend you to use one line per
sentence.
You can read {one-sentence-per-line}[this article] to know more benefit you can gain.

== Footer

Footer should contains all the collaborators's name and email. If someone
mention a bug, attach "Reported-by: Tom <\Tom@example.com>". If someone
help you test the code, attach "Tested-by: Sam <\Sam@example.com>".

If you are using GPG to sign your commit, you can attach your name at the end
of the rooter like: "Signed-off-by: Yourname <\name@example.com>".

== Full Example

----
F!/popup/push: fix action push elsewhere

= Major fixes
First of all, the push elsewhere action fail to refresh pop up status.
This is because it didn't pass the `popup` variable.

Secondly, the `git.branch.prompt_for_branch()` function needs a list of
branches to test if arguments are contained in options.
But the original code just calls it without any arguments.
So I provide `git.branch.get_all_branches()` to generate necessary
arguments.

Besides, I truncate the unexpected git branch in commit {commit-link}[12f8e16].

= BREAKING CHANGE:
* git.branch.get_local_branches is now private

Fixes: #233

:commit-link: https://github.com/user/project/commit/12f8e166965e8b706d3b54876f92d3e6052f5c84

Signed-off-by: Avimitin <avimitin@gmail.com>
----

== Template usage

You can use my commit template:

----
git clone https://github.com/Avimitin/commit-convention.git
git config --global commit.template $PWD/commit-convention/template.txt
----

== How to generate changelogs

[source, bash]
----
git log --oneline --pretty="format:%s" {RANGE} | sed 's/[A-Z]!*\/*//'
----

== Credit

This convention is inspired by the below project:

* Simplistic Commits: https://github.com/bnoctis/simplistic-commits
* Conventional Commits: https://www.conventionalcommits.org/en/v1.0.0/
* How to write commit message: https://chris.beams.io/posts/git-commit/

== License

https://creativecommons.org/licenses/by/4.0/[CC-BY-4.0]

(c) 2021 Avimitin
